import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
    header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, borderBottomWidth: 2, borderBottomStyle: 'solid', borderBottomColor: '#1A73E8', paddingBottom: 10 },
    headerTitle: { fontSize: 24, color: '#1A73E8', fontWeight: 'bold' },
    headerSub: { fontSize: 10, color: '#666' },
    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 10, color: '#999', textAlign: 'center', borderTop: '1px solid #eee', paddingTop: 10 },
    title: { fontSize: 28, fontWeight: 'bold', marginBottom: 10, color: '#333' },
    subtitle: { fontSize: 14, color: '#666', marginBottom: 20 },
    sectionTitle: { fontSize: 18, color: '#1A73E8', marginTop: 20, marginBottom: 10, borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: '#eee', paddingBottom: 5 },

    // Grid/Cards
    grid2x2: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginTop: 10 },
    card: { width: '48%', backgroundColor: '#f8f9fa', padding: 15, borderRadius: 8, marginBottom: 15, borderWidth: 1, borderStyle: 'solid', borderColor: '#eee' },
    cardTitle: { fontSize: 12, color: '#666', marginBottom: 5 },
    cardValue: { fontSize: 20, fontWeight: 'bold', color: '#1A73E8' },

    // Tables
    table: { width: '100%', marginTop: 10 },
    tableRow: { flexDirection: 'row', borderBottom: '1px solid #eee', paddingVertical: 8, alignItems: 'center' },
    tableHeader: { backgroundColor: '#f8f9fa', fontWeight: 'bold' },
    tableCell: { flex: 1, fontSize: 10, color: '#333' },
    tableCellNum: { flex: 1, fontSize: 10, color: '#333', textAlign: 'right' },

    text: { fontSize: 11, color: '#333', lineHeight: 1.5, marginBottom: 5 },
    bulletList: { marginLeft: 10, marginTop: 5 },
    bulletItem: { fontSize: 11, color: '#333', marginBottom: 5 },

    // Specific blocks
    coverBox: { backgroundColor: '#1A73E8', padding: 40, borderRadius: 10, marginTop: 50 },
    coverTitle: { color: 'white', fontSize: 36, fontWeight: 'bold', marginBottom: 10 },
    coverSub: { color: '#e8f0fe', fontSize: 16 },
    highlightBox: { backgroundColor: '#e8f0fe', padding: 15, borderRadius: 5, marginTop: 10, borderLeft: '4px solid #1A73E8' },
    heatmapRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 2, marginTop: 10 },
    heatmapCell: { width: 45, height: 45, justifyContent: 'center', alignItems: 'center', backgroundColor: '#e8f0fe', margin: 2, borderRadius: 4 },
    heatmapText: { fontSize: 8, color: '#1A73E8' },
});

export const EnergyReport = ({ data }: { data: any }) => {
    const { meta, summary, appliance_breakdown, category_breakdown, bill_detail, bill_history, ai_insights, heatmap_data, peer_comparison } = data;

    const Header = () => (
        <View style={styles.header} fixed>
            <Text style={styles.headerTitle}>VoltIQ</Text>
            <View>
                <Text style={{ ...styles.headerSub, textAlign: 'right' }}>{meta.home_name}</Text>
                <Text style={{ ...styles.headerSub, textAlign: 'right' }}>{meta.month} Report</Text>
            </View>
        </View>
    );

    const Footer = () => (
        <View style={styles.footer} fixed>
            <Text render={({ pageNumber, totalPages }) => (
                `Generated by VoltIQ — AI Home Energy Intelligence Platform | Page ${pageNumber} of 6`
            )} />
        </View>
    );

    return (
        <Document>
            {/* PAGE 1: COVER */}
            <Page size="A4" style={styles.page}>
                <View style={styles.coverBox}>
                    <Text style={styles.coverTitle}>Home Energy Report</Text>
                    <Text style={styles.coverSub}>{meta.home_name}</Text>
                    <Text style={{ ...styles.coverSub, marginTop: 20 }}>Period: {meta.month}</Text>
                    <Text style={styles.coverSub}>Generated on {meta.generated_at}</Text>
                </View>

                <View style={{ ...styles.grid2x2, marginTop: 50 }}>
                    <View style={{ ...styles.card, width: '30%' }}>
                        <Text style={styles.cardTitle}>Total Usage</Text>
                        <Text style={styles.cardValue}>{summary.total_kwh} kWh</Text>
                    </View>
                    <View style={{ ...styles.card, width: '30%' }}>
                        <Text style={styles.cardTitle}>Total Cost</Text>
                        <Text style={styles.cardValue}>₹{summary.total_bill_inr}</Text>
                    </View>
                    <View style={{ ...styles.card, width: '30%', backgroundColor: '#e8f0fe', borderColor: '#1A73E8' }}>
                        <Text style={styles.cardTitle}>Efficiency Grade</Text>
                        <Text style={styles.cardValue}>{summary.efficiency_grade}</Text>
                    </View>
                </View>
                <Footer />
            </Page>

            {/* PAGE 2: EXECUTIVE SUMMARY */}
            <Page size="A4" style={styles.page}>
                <Header />
                <Text style={styles.title}>Executive Summary</Text>

                <View style={styles.grid2x2}>
                    <View style={styles.card}>
                        <Text style={styles.cardTitle}>Monthly Usage</Text>
                        <Text style={styles.cardValue}>{summary.total_kwh} kWh</Text>
                        <Text style={{ fontSize: 10, color: summary.mom_change_pct <= 0 ? '#34a853' : '#ea4335', marginTop: 5 }}>
                            {summary.mom_change_pct <= 0 ? '↓' : '↑'} {Math.abs(summary.mom_change_pct)}% from last month
                        </Text>
                    </View>
                    <View style={styles.card}>
                        <Text style={styles.cardTitle}>Estimated Bill</Text>
                        <Text style={styles.cardValue}>₹{summary.total_bill_inr}</Text>
                    </View>
                    <View style={styles.card}>
                        <Text style={styles.cardTitle}>Carbon Footprint</Text>
                        <Text style={styles.cardValue}>{summary.co2_kg} kg CO₂</Text>
                    </View>
                    <View style={styles.card}>
                        <Text style={styles.cardTitle}>Sustainability Score</Text>
                        <Text style={styles.cardValue}>{summary.sustainability_score}/100</Text>
                    </View>
                </View>

                <View style={styles.highlightBox}>
                    <Text style={{ fontSize: 12, fontWeight: 'bold', color: '#1A73E8', marginBottom: 5 }}>AI Key Finding</Text>
                    <Text style={styles.text}>{ai_insights.forecast?.reasoning || 'Forecast generated from recent data patterns.'}</Text>
                </View>

                <Text style={styles.sectionTitle}>Anomalies Detected</Text>
                <View style={styles.bulletList}>
                    {ai_insights.anomalies.map((a: any, i: number) => (
                        <Text key={i} style={styles.bulletItem}>• {a.explanation || `Anomaly detected in ${a.month}`}</Text>
                    ))}
                </View>
                <Footer />
            </Page>

            {/* PAGE 3: CONSUMPTION BREAKDOWN */}
            <Page size="A4" style={styles.page}>
                <Header />
                <Text style={styles.title}>Consumption Breakdown</Text>

                <Text style={styles.sectionTitle}>Appliance Usage (Top Consumers)</Text>
                <View style={styles.table}>
                    <View style={{ ...styles.tableRow, ...styles.tableHeader }}>
                        <Text style={{ ...styles.tableCell, flex: 2 }}>Appliance</Text>
                        <Text style={styles.tableCell}>Category</Text>
                        <Text style={styles.tableCellNum}>Usage (kWh)</Text>
                        <Text style={styles.tableCellNum}>Cost (₹)</Text>
                        <Text style={styles.tableCellNum}>% of Bill</Text>
                    </View>
                    {appliance_breakdown.map((app: any, i: number) => (
                        <View key={i} style={styles.tableRow}>
                            <Text style={{ ...styles.tableCell, flex: 2 }}>{app.name}</Text>
                            <Text style={styles.tableCell}>{app.category}</Text>
                            <Text style={styles.tableCellNum}>{app.monthly_kwh}</Text>
                            <Text style={styles.tableCellNum}>{app.cost_inr}</Text>
                            <Text style={styles.tableCellNum}>{app.pct_of_bill}%</Text>
                        </View>
                    ))}
                </View>

                <Text style={styles.sectionTitle}>Usage by Category</Text>
                <View style={styles.table}>
                    <View style={{ ...styles.tableRow, ...styles.tableHeader }}>
                        <Text style={{ ...styles.tableCell, flex: 2 }}>Category</Text>
                        <Text style={styles.tableCellNum}>Usage (kWh)</Text>
                        <Text style={styles.tableCellNum}>Cost (₹)</Text>
                        <Text style={styles.tableCellNum}>% Total</Text>
                    </View>
                    {category_breakdown.map((cat: any, i: number) => (
                        <View key={i} style={styles.tableRow}>
                            <Text style={{ ...styles.tableCell, flex: 2 }}>{cat.category}</Text>
                            <Text style={styles.tableCellNum}>{cat.kwh}</Text>
                            <Text style={styles.tableCellNum}>{cat.cost_inr}</Text>
                            <Text style={styles.tableCellNum}>{cat.pct}%</Text>
                        </View>
                    ))}
                </View>

                <Text style={styles.sectionTitle}>Daily Consumption Heatmap (kWh)</Text>
                <View style={styles.heatmapRow}>
                    {heatmap_data.map((h: any, i: number) => (
                        <View key={i} style={{ ...styles.heatmapCell, backgroundColor: h.kwh > 20 ? '#fce8e6' : h.kwh > 15 ? '#fef7e0' : '#e8f0fe' }}>
                            <Text style={{ ...styles.heatmapText, color: h.kwh > 20 ? '#ea4335' : h.kwh > 15 ? '#fbbc04' : '#1A73E8' }}>{h.kwh}</Text>
                            <Text style={{ fontSize: 6, color: '#999' }}>{i + 1}</Text>
                        </View>
                    ))}
                </View>
                <Footer />
            </Page>

            {/* PAGE 4: BILL ANALYSIS */}
            <Page size="A4" style={styles.page}>
                <Header />
                <Text style={styles.title}>Bill Analysis</Text>

                <Text style={styles.sectionTitle}>Itemized Charges</Text>
                <View style={styles.table}>
                    <View style={styles.tableRow}>
                        <Text style={{ ...styles.tableCell, flex: 2 }}>Energy Charge</Text>
                        <Text style={styles.tableCellNum}>₹{bill_detail.energy_charge}</Text>
                    </View>
                    <View style={styles.tableRow}>
                        <Text style={{ ...styles.tableCell, flex: 2 }}>Fixed Charge</Text>
                        <Text style={styles.tableCellNum}>₹{bill_detail.fixed_charge}</Text>
                    </View>
                    <View style={styles.tableRow}>
                        <Text style={{ ...styles.tableCell, flex: 2 }}>Fuel Surcharge</Text>
                        <Text style={styles.tableCellNum}>₹{bill_detail.fuel_surcharge}</Text>
                    </View>
                    <View style={styles.tableRow}>
                        <Text style={{ ...styles.tableCell, flex: 2 }}>Duty / Taxes</Text>
                        <Text style={styles.tableCellNum}>₹{bill_detail.duty}</Text>
                    </View>
                    <View style={{ ...styles.tableRow, backgroundColor: '#f8f9fa' }}>
                        <Text style={{ ...styles.tableCell, flex: 2, fontWeight: 'bold' }}>Total Bill</Text>
                        <Text style={{ ...styles.tableCellNum, fontWeight: 'bold', color: '#1A73E8' }}>₹{bill_detail.total}</Text>
                    </View>
                </View>

                <Text style={styles.sectionTitle}>Slab Breakdown</Text>
                <View style={styles.table}>
                    <View style={{ ...styles.tableRow, ...styles.tableHeader }}>
                        <Text style={styles.tableCell}>Slab Range</Text>
                        <Text style={styles.tableCellNum}>Units (kWh)</Text>
                        <Text style={styles.tableCellNum}>Rate (₹/kWh)</Text>
                        <Text style={styles.tableCellNum}>Charge (₹)</Text>
                    </View>
                    {bill_detail.slab_breakdown.map((s: any, i: number) => (
                        <View key={i} style={styles.tableRow}>
                            <Text style={styles.tableCell}>{s.range}</Text>
                            <Text style={styles.tableCellNum}>{s.units}</Text>
                            <Text style={styles.tableCellNum}>{s.rate}</Text>
                            <Text style={styles.tableCellNum}>{s.charge}</Text>
                        </View>
                    ))}
                </View>

                <Text style={styles.sectionTitle}>6-Month History</Text>
                <View style={styles.table}>
                    <View style={{ ...styles.tableRow, ...styles.tableHeader }}>
                        <Text style={styles.tableCell}>Month</Text>
                        <Text style={styles.tableCellNum}>Usage (kWh)</Text>
                        <Text style={styles.tableCellNum}>Amount (₹)</Text>
                    </View>
                    {bill_history.map((b: any, i: number) => (
                        <View key={i} style={styles.tableRow}>
                            <Text style={styles.tableCell}>{b.month}</Text>
                            <Text style={styles.tableCellNum}>{b.kwh}</Text>
                            <Text style={styles.tableCellNum}>{b.amount}</Text>
                        </View>
                    ))}
                </View>
                <Footer />
            </Page>

            {/* PAGE 5: AI RECOMMENDATIONS */}
            <Page size="A4" style={styles.page}>
                <Header />
                <Text style={styles.title}>AI Recommendations</Text>

                <View style={{ marginTop: 20 }}>
                    {ai_insights.top_recommendations.map((rec: any, i: number) => (
                        <View key={i} style={{ marginBottom: 20, padding: 15, borderWidth: 1, borderStyle: 'solid', borderColor: '#eee', borderRadius: 8 }}>
                            <Text style={{ fontSize: 14, fontWeight: 'bold', color: '#1A73E8', marginBottom: 5 }}>
                                {i + 1}. {rec.action}
                            </Text>
                            <View style={{ flexDirection: 'row', marginTop: 10 }}>
                                <View style={{ flex: 1 }}>
                                    <Text style={{ fontSize: 10, color: '#666' }}>Effort Rating</Text>
                                    <Text style={{ fontSize: 12 }}>{rec.effort}/5</Text>
                                </View>
                                <View style={{ flex: 1 }}>
                                    <Text style={{ fontSize: 10, color: '#666' }}>Annual Savings</Text>
                                    <Text style={{ fontSize: 12, fontWeight: 'bold', color: '#34a853' }}>₹{rec.saving}</Text>
                                </View>
                                <View style={{ flex: 1 }}>
                                    <Text style={{ fontSize: 10, color: '#666' }}>Payback Period</Text>
                                    <Text style={{ fontSize: 12 }}>{rec.payback}</Text>
                                </View>
                            </View>
                        </View>
                    ))}
                </View>

                <View style={{ ...styles.highlightBox, backgroundColor: '#e6f4ea', borderLeftColor: '#34a853' }}>
                    <Text style={{ fontSize: 14, fontWeight: 'bold', color: '#0d652d', textAlign: 'center', marginBottom: 5 }}>
                        Potential Savings Summary
                    </Text>
                    <Text style={{ fontSize: 12, color: '#0d652d', textAlign: 'center' }}>
                        Implementing all recommendations saves ₹{ai_insights.top_recommendations.reduce((acc: number, r: any) => acc + r.saving, 0)}/year
                    </Text>
                </View>
                <Footer />
            </Page>

            {/* PAGE 6: SUSTAINABILITY SCORECARD */}
            <Page size="A4" style={styles.page}>
                <Header />
                <Text style={styles.title}>Sustainability Scorecard</Text>

                <View style={{ alignItems: 'center', marginVertical: 40 }}>
                    <View style={{ width: 150, height: 150, borderRadius: 75, backgroundColor: '#e6f4ea', justifyContent: 'center', alignItems: 'center', borderWidth: 5, borderStyle: 'solid', borderColor: '#34a853' }}>
                        <Text style={{ fontSize: 48, fontWeight: 'bold', color: '#0d652d' }}>{summary.sustainability_score}</Text>
                        <Text style={{ fontSize: 12, color: '#0d652d' }}>Score</Text>
                    </View>
                </View>

                <Text style={styles.sectionTitle}>Environmental Impact</Text>
                <View style={styles.grid2x2}>
                    <View style={styles.card}>
                        <Text style={styles.cardTitle}>CO₂ Emissions</Text>
                        <Text style={styles.cardValue}>{summary.co2_kg} kg</Text>
                    </View>
                    <View style={styles.card}>
                        <Text style={styles.cardTitle}>Equivalent Trees Planted</Text>
                        <Text style={styles.cardValue}>{Math.round(summary.co2_kg / 21)} trees</Text>
                    </View>
                    <View style={styles.card}>
                        <Text style={styles.cardTitle}>Equivalent Car Travel</Text>
                        <Text style={styles.cardValue}>{Math.round(summary.co2_kg * 4.1)} km</Text>
                    </View>
                </View>

                <Text style={styles.sectionTitle}>Peer Comparison</Text>
                <View style={styles.highlightBox}>
                    <Text style={{ fontSize: 14, color: '#1A73E8', textAlign: 'center', marginBottom: 10 }}>
                        Your Usage: {peer_comparison.user_kwh} kWh | Peer Average: {peer_comparison.peer_avg_kwh} kWh
                    </Text>
                    <Text style={{ fontSize: 12, color: '#666', textAlign: 'center' }}>
                        You use {Math.max(0, Math.round((1 - peer_comparison.user_kwh / peer_comparison.peer_avg_kwh) * 100))}% less energy than similar homes in your region.
                    </Text>
                </View>

                <Text style={{ fontSize: 12, color: '#666', marginTop: 20 }}>
                    Component Efficiency Grade: {ai_insights.efficiency_grade || 'B'}
                </Text>

                <Footer />
            </Page>
        </Document>
    );
};
